### PR TITLE
25megs is enough

### PR DESCRIPTION
**Pull request by ammgws**

### CODE REVIEW

**Comment by WnndGws** [comment]
Why limit at all though?

**Comment by ammgws** [comment]
Abbot

**Comment by ammgws** [comment]
Abbot

**Comment by WnndGws** [comment]
But then why have such a very high limit? Seems like limit should either be low so as to work on low bandwidth networks, or not at all to take advantage of high bandwidth networks?

**Comment by ammgws** [comment]
Whoosh? https://www.computerworld.com.au/article/525840/his_own_words_tony_abbott_nbn/

**Comment by WnndGws** [comment]
Whoosh

**Pull request closed without merging**
